root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - prettier
plugins:
  - '@typescript-eslint'
  - react-hooks
  - prettier
rules:
  prettier/prettier: warn
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: after-used
      ignoreRestSiblings: false
  no-console: warn
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.base.json'
