root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react-hooks/recommended
  - prettier
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
    node: true
plugins:
  - '@typescript-eslint'
  - react-hooks
  - prettier
rules:
  prettier/prettier: warn
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: after-used
      ignoreRestSiblings: false
  no-console: warn
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  import/no-default-export: error
  import/no-unresolved: off

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.base.json'
